import { supabase } from '../../supabase';
import React, { useEffect, useState } from 'react';
import { useAuth } from '../../contexts/AuthContext';
import { useTenant } from '../../hooks/useTenant';
import { useTheme } from '../../contexts/ThemeContext';
import { useToast } from '../../hooks/useToast';
import { CloudinaryUpload } from '../../components/CloudinaryUpload';
import { Link } from 'react-router-dom';
import { Save, Loader2, Info, Zap, Star, Trophy, Lock, Eye, EyeOff, BadgeCheck } from 'lucide-react';
import { getClubPalette } from '../../theme/racPalette';

/**
 * ------------------------------------------------------------------
 * Visual identity — reuses DashboardHome.tsx's actual patterns rather
 * than re-approximating them, so the two pages can't quietly drift
 * apart. Ported directly (not just "in spirit"):
 *   - club-palette resolution (tenant.id + light/dark)
 *   - forced-Inter scoped override + INTER_FONT_URL/INTER_LINK_ID
 *   - the page-top "label + live clock" header row (formatClock())
 *   - the .rac-welcome-card / .rac-welcome-id / .rac-welcome-meta CSS
 *     trio verbatim, including its comment — this exists specifically
 *     because flexWrap+space-between collapses to flex-start with only
 *     two children, which reads as "floating" text. Reimplementing
 *     this header freehand on a second page would silently reintroduce
 *     that exact bug, so the class contract is reused as-is rather
 *     than rebuilt.
 *   - section-header row shape: label + `···` affordance on the same
 *     line, used by every DashboardHome card (Reflection, Member
 *     engagement, Needs attention, Tracking, Attendance rate) — this
 *     page's section headers now carry the same dot instead of being
 *     bare text.
 *   - the loading-skeleton shape (role="status", aria-busy, pulsing
 *     p.dark blocks at the same radius/spacing)
 * See DashboardHome's own header comment for the full reasoning on why
 * this page opts out of the tenant theme system on purpose.
 *
 * Data model: this page keeps its own fetch against `users` (id +
 * tenant_id), exactly as the pre-restyle DashboardProfile.tsx did —
 * useAuth().profile is used only to paint the header instantly on
 * first render (name + photo, same as DashboardHome's welcome card),
 * then formData takes over the moment the real row lands. Editable
 * fields (phone, dob, address, school, grade, bloodGroup,
 * emergencyPhone, emergencyDetails, rotaryMemberId) are NOT assumed to
 * exist on useAuth's profile object — only on the `users` row — since
 * that's the one place this schema is actually confirmed.
 *
 * CHANGELOG (this revision):
 *   - Role display now resolves against the tenant's `roles` table
 *     (same roleById pattern AdminMembers.tsx uses) instead of raw
 *     formData.role_id / formData.role text — previously this page had
 *     no role display at all in the editable form; the Club Role box in
 *     the left rail now shows the same label+color chip AdminMembers
 *     shows in its table ("Member" text label was previously the raw
 *     column with a fallback string, decoupled from the actual roles
 *     table — that was the bug: a member's role label could silently
 *     disagree with what the admin panel shows for the same person).
 *   - Added `rotaryMemberId` (official Rotary/Interact International
 *     ID) — editable here by the member, and also editable by admins in
 *     AdminMembers. Distinct from `memberId` (internally generated,
 *     admin-only, shown read-only below).
 *   - Added a read-only "Assigned Member ID" display of `memberId` —
 *     generated by the admin panel, never editable by the member.
 *   - Added a profile-completion % bar covering every member-editable
 *     field (name, phone, dob, address, school, grade, bloodGroup,
 *     emergencyPhone, emergencyDetails, rotaryMemberId, photo).
 * ------------------------------------------------------------------
 */

const INTER_FONT_URL = 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap';
const INTER_LINK_ID = 'rac-dashboard-inter-font';

function useInterFont() {
  useEffect(() => {
    if (document.getElementById(INTER_LINK_ID)) return;
    const link = document.createElement('link');
    link.id = INTER_LINK_ID;
    link.rel = 'stylesheet';
    link.href = INTER_FONT_URL;
    document.head.appendChild(link);
  }, []);
}

/** 12-hour clock label, e.g. "3:21 PM" — identical to DashboardHome's
 * formatClock(), reused verbatim so the page-top header stays
 * consistent across every page in the shell rather than this page
 * being the one place the live clock silently disappears. */
function formatClock(d: Date) {
  let h = d.getHours();
  const m = d.getMinutes();
  const ampm = h >= 12 ? 'PM' : 'AM';
  h = h % 12;
  h = h ? h : 12;
  const mm = m < 10 ? `0${m}` : `${m}`;
  return `${h}:${mm} ${ampm}`;
}

const BLOOD_GROUPS = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];

/** Fields the user is never allowed to edit directly — stripped from
 * the payload on save. Mirrors the original page's destructure list;
 * status/role/join-date/memberId stay admin-managed. rotaryMemberId is
 * intentionally NOT in this list — it's member-editable. */
const NON_EDITABLE_KEYS = ['xp', 'fp', 'level', 'role', 'role_id', 'status', 'id', 'email', 'tenant_id', 'created_at', 'updatedAt', 'memberId'] as const;

/** Interface for a role row, matching AdminMembers.tsx's RoleRow exactly
 * so the role chip rendered here can never drift from what the admin
 * panel shows for the same person. */
interface RoleRow { id: string; name: string; label: string; color: string; is_system: boolean; }

/** Fields that count toward the profile-completion % — every field the
 * member themselves can fill in on this page. Deliberately excludes
 * admin-managed fields (role, status, joiningDate, memberId) since a
 * member has no control over those, and excludes the password fields
 * since they aren't part of the persisted profile row. */
const COMPLETION_FIELDS: { key: string; label: string }[] = [
  { key: 'name', label: 'Full name' },
  { key: 'photo', label: 'Profile photo' },
  { key: 'phone', label: 'Phone number' },
  { key: 'dob', label: 'Date of birth' },
  { key: 'address', label: 'Address' },
  { key: 'school', label: 'School / institution' },
  { key: 'grade', label: 'Grade / class' },
  { key: 'bloodGroup', label: 'Blood group' },
  { key: 'emergencyPhone', label: 'Emergency contact phone' },
  { key: 'emergencyDetails', label: 'Emergency contact details' },
  { key: 'rotaryMemberId', label: 'Rotary Member ID' },
];

function computeCompletion(data: any) {
  const filled = COMPLETION_FIELDS.filter((f) => {
    const v = data?.[f.key];
    return typeof v === 'string' ? v.trim().length > 0 : !!v;
  });
  const pct = COMPLETION_FIELDS.length > 0 ? Math.round((filled.length / COMPLETION_FIELDS.length) * 100) : 0;
  return { pct, filledCount: filled.length, total: COMPLETION_FIELDS.length, missing: COMPLETION_FIELDS.filter((f) => !filled.includes(f)) };
}

export default function DashboardProfile() {
  const { profile, user } = useAuth();
  const { tenant } = useTenant();
  const { addToast } = useToast();
  const { resolvedTheme } = useTheme();
  const dark = resolvedTheme === 'dark';
  const p = getClubPalette(tenant.id, dark ? 'dark' : 'light');

  useInterFont();

  // Live clock — identical cadence to DashboardHome's (refreshed every
  // 30s, not every second; this is a page-header clock, not a stopwatch).
  const [clockLabel, setClockLabel] = useState(() => formatClock(new Date()));
  useEffect(() => {
    const id = setInterval(() => setClockLabel(formatClock(new Date())), 30000);
    return () => clearInterval(id);
  }, []);

  const [formData, setFormData] = useState<any>({});
  const [roles, setRoles] = useState<RoleRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);

  const [currentPassword, setCurrentPassword] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [showCurrentPw, setShowCurrentPw] = useState(false);
  const [showNewPw, setShowNewPw] = useState(false);
  const [changingPassword, setChangingPassword] = useState(false);

  const fetchProfile = React.useCallback(async () => {
    const userId = user?.id;
    if (!userId) return;
    setLoading(true);
    setError(null);
    try {
      const [{ data, error: fetchError }, { data: roleData, error: roleError }] = await Promise.all([
        supabase.from('users').select('*').eq('id', userId).eq('tenant_id', tenant.id).single(),
        supabase.from('roles').select('*').eq('tenant_id', tenant.id),
      ]);
      if (fetchError) throw fetchError;
      if (roleError) throw roleError;
      if (data) setFormData(data);
      setRoles((roleData || []) as RoleRow[]);
    } catch (err) {
      console.error(err);
      setError("Couldn't load your profile data.");
    } finally {
      setLoading(false);
    }
  }, [user, tenant.id]);

  useEffect(() => {
    fetchProfile();
  }, [fetchProfile]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData((prev: any) => ({ ...prev, [name]: value }));
  };

  const handleSave = async () => {
    if (!user) return;
    setSaving(true);
    try {
      const editableFields = { ...formData };
      NON_EDITABLE_KEYS.forEach((key) => delete editableFields[key]);
      const { error: saveError } = await supabase
        .from('users')
        .update({ ...editableFields, updatedAt: new Date().toISOString() })
        .eq('id', user.id)
        .eq('tenant_id', tenant.id);
      if (saveError) throw saveError;
      addToast('Profile updated successfully!', 'success');
    } catch (err) {
      console.error(err);
      addToast('Failed to update profile.', 'error');
    } finally {
      setSaving(false);
    }
  };

  const handlePasswordChange = async () => {
    if (!user?.email) return;
    if (!currentPassword || !newPassword || !confirmPassword) {
      addToast('Please fill in all password fields.', 'error');
      return;
    }
    if (newPassword.length < 8) {
      addToast('New password must be at least 8 characters.', 'error');
      return;
    }
    if (newPassword !== confirmPassword) {
      addToast('New password and confirmation do not match.', 'error');
      return;
    }
    if (newPassword === currentPassword) {
      addToast('New password must be different from your current password.', 'error');
      return;
    }

    setChangingPassword(true);
    try {
      const { error: verifyError } = await supabase.auth.signInWithPassword({
        email: user.email,
        password: currentPassword,
      });
      if (verifyError) {
        addToast('Current password is incorrect.', 'error');
        return;
      }
      const { error: updateError } = await supabase.auth.updateUser({ password: newPassword });
      if (updateError) throw updateError;

      addToast('Password changed successfully!', 'success');
      setCurrentPassword('');
      setNewPassword('');
      setConfirmPassword('');
    } catch (err) {
      console.error(err);
      addToast('Failed to change password.', 'error');
    } finally {
      setChangingPassword(false);
    }
  };

  const displayName = formData.name || profile?.name || 'there';
  const displayPhoto = formData.photo || (profile as any)?.photo;

  // Role now resolves against the real roles table, exactly like
  // AdminMembers.tsx's roleById — this is the fix for role display
  // disagreeing with the admin panel. formData.role_id is the FK; if a
  // legacy row only ever stored a raw `role` string, that's used as a
  // last-resort label fallback, but the color chip only renders once a
  // real roles-table match is found.
  const currentRole = roles.find((r) => r.id === formData.role_id) || null;
  const roleLabel = currentRole?.label || formData.role || 'Member';
  const roleColor = currentRole?.color || '#9ca3af';

  const completion = computeCompletion(formData);

  if (loading) {
    return (
      <div
        role="status"
        aria-busy="true"
        aria-label="Loading profile"
        style={{ background: p.bg, padding: 18 }}
        className="p-4 md:p-8 -m-4 md:-m-8"
      >
        <div style={{ maxWidth: 960, margin: '0 auto' }}>
          <div
            style={{ height: 96, borderRadius: 20, marginBottom: 12, background: p.dark, border: `1px solid ${p.border}`, opacity: 0.5 }}
            className="animate-pulse"
          />
          <div
            style={{ height: 64, borderRadius: 20, marginBottom: 12, background: p.dark, border: `1px solid ${p.border}`, opacity: 0.5 }}
            className="animate-pulse"
          />
          <div
            style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: 12 }}
            className="!grid-cols-1 lg:!grid-cols-[1fr_2fr]"
          >
            <div style={{ height: 340, borderRadius: 20, background: p.dark, border: `1px solid ${p.border}`, opacity: 0.5 }} className="animate-pulse" />
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
              {[0, 1, 2].map((i) => (
                <div key={i} style={{ height: 180, borderRadius: 20, background: p.dark, border: `1px solid ${p.border}`, opacity: 0.5 }} className="animate-pulse" />
              ))}
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="rac-dashboard-profile">
      {/* rac-welcome-card / rac-welcome-id / rac-welcome-meta: reused
          verbatim from DashboardHome.tsx. See that file's header
          comment for why this exact class trio exists instead of a
          freehand flexWrap+space-between layout. */}
      <style>{`
        .rac-dashboard-profile, .rac-dashboard-profile * {
          font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif !important;
        }
        .rac-dashboard-profile ::-webkit-scrollbar { display: none; }

        .rac-welcome-card {
          display: flex;
          justify-content: space-between;
          align-items: center;
          gap: 16px;
        }
        .rac-welcome-id {
          display: flex;
          align-items: center;
          gap: 14px;
          min-width: 0;
        }
        .rac-welcome-meta {
          text-align: right;
          line-height: 1.5;
          flex-shrink: 0;
        }
        @media (max-width: 520px) {
          .rac-welcome-card {
            flex-direction: column;
            align-items: flex-start;
          }
          .rac-welcome-id {
            width: 100%;
          }
          .rac-welcome-meta {
            text-align: left;
            width: 100%;
            margin-top: 4px;
            padding-top: 10px;
            border-top: 1px solid ${p.border};
          }
        }

        .rac-field label {
          display: block;
          font-size: 10.5px;
          font-weight: 600;
          text-transform: uppercase;
          letter-spacing: .04em;
          margin-bottom: 6px;
        }
        .rac-field input,
        .rac-field select,
        .rac-field textarea {
          width: 100%;
          font-size: 13.5px;
          border-radius: 10px;
          padding: 9px 12px;
          font-family: inherit;
          transition: border-color .15s, background .15s;
        }
        .rac-field input:focus,
        .rac-field select:focus,
        .rac-field textarea:focus {
          outline: none;
        }
        .rac-field input:disabled {
          cursor: not-allowed;
          opacity: .6;
        }
      `}</style>

      <div style={{ background: p.bg, padding: 18, transition: 'background .25s' }} className="p-4 md:p-8 -m-4 md:-m-8">
        <div style={{ maxWidth: 960, margin: '0 auto' }}>
          {/* ---------------- page-top: title + live clock ---------------- */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 12, padding: '0 2px', gap: 12 }}>
            <span style={{ fontSize: 19, fontWeight: 600, color: p.ptxt, letterSpacing: '-.2px', flexShrink: 0 }}>Profile</span>
            <span style={{ fontSize: 24, color: p.ptxt, fontWeight: 600 }}>{clockLabel}</span>
          </div>

          {error && (
            <div
              role="alert"
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                gap: 12,
                padding: 14,
                borderRadius: 12,
                marginBottom: 12,
                background: '#3a1a14',
                color: '#e08a72',
              }}
            >
              <p style={{ fontSize: 13, fontWeight: 600, margin: 0 }}>{error}</p>
              <button
                onClick={fetchProfile}
                style={{ fontSize: 11, fontWeight: 700, textTransform: 'uppercase', textDecoration: 'underline', background: 'none', border: 'none', color: 'inherit', cursor: 'pointer' }}
              >
                Retry
              </button>
            </div>
          )}

          {/* ---------------- welcome card ---------------- */}
          <div
            className="rac-welcome-card"
            style={{
              borderRadius: 20,
              padding: '20px 22px',
              marginBottom: 12,
              background: p.dark,
              color: p.tl,
              border: `1px solid ${p.border}`,
            }}
          >
            <div className="rac-welcome-id">
              {displayPhoto ? (
                <img
                  src={displayPhoto}
                  alt={displayName}
                  style={{
                    width: 44,
                    height: 44,
                    borderRadius: 12,
                    objectFit: 'cover',
                    flexShrink: 0,
                    border: `1px solid ${p.border}`,
                    boxShadow: '0 2px 6px rgba(0,0,0,.25)',
                  }}
                />
              ) : (
                <div
                  style={{
                    width: 44,
                    height: 44,
                    borderRadius: 12,
                    background: `linear-gradient(135deg, ${p.av2}, ${p.green})`,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontWeight: 700,
                    fontSize: 16,
                    color: '#1b0c12',
                    flexShrink: 0,
                    border: `1px solid ${p.border}`,
                    boxShadow: '0 2px 6px rgba(0,0,0,.25)',
                  }}
                >
                  {displayName.charAt(0).toUpperCase()}
                </div>
              )}
              <div style={{ minWidth: 0 }}>
                <div style={{ fontSize: 11, color: p.tsub, fontWeight: 500, marginBottom: 2 }}>Manage your account</div>
                <div
                  style={{
                    fontSize: 18,
                    fontWeight: 700,
                    letterSpacing: '-.2px',
                    whiteSpace: 'nowrap',
                    overflow: 'hidden',
                    textOverflow: 'ellipsis',
                  }}
                >
                  {displayName}
                </div>
              </div>
            </div>
            <div className="rac-welcome-meta">
              <button
                onClick={handleSave}
                disabled={saving}
                style={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  gap: 8,
                  background: p.green,
                  color: '#1b0c12',
                  border: 'none',
                  borderRadius: 12,
                  padding: '10px 18px',
                  fontSize: 13,
                  fontWeight: 700,
                  cursor: saving ? 'default' : 'pointer',
                  opacity: saving ? 0.7 : 1,
                }}
              >
                {saving ? <Loader2 size={16} className="animate-spin" /> : <Save size={16} />}
                Save Changes
              </button>
            </div>
          </div>

          {/* ---------------- profile completion card ----------------
              Same "dark card + header row + ··· affordance" shape as
              every DashboardHome card. Percent is computed client-side
              from COMPLETION_FIELDS — no backend column needed since
              it's fully derivable from the row already loaded. */}
          <div style={{ borderRadius: 20, padding: 16, marginBottom: 12, background: p.dark, color: p.tl, border: `1px solid ${p.border}` }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
              <span style={{ fontSize: 13, fontWeight: 600 }}>Profile completion</span>
              <span style={{ fontSize: 13, fontWeight: 700, color: p.green }}>{completion.pct}%</span>
            </div>
            <div style={{ height: 8, background: p.border, borderRadius: 6, overflow: 'hidden' }}>
              <div
                style={{
                  height: '100%',
                  width: `${completion.pct}%`,
                  background: p.green,
                  borderRadius: 6,
                  transition: 'width .35s ease',
                }}
              />
            </div>
            <div style={{ fontSize: 10.5, color: p.tsub, marginTop: 9 }}>
              {completion.pct === 100
                ? 'Your profile is fully complete.'
                : `${completion.filledCount} of ${completion.total} fields complete${
                    completion.missing.length > 0 ? ` — missing ${completion.missing.map((f) => f.label).join(', ')}` : ''
                  }`}
            </div>
          </div>

          {/* ---------------- admin-managed notice ---------------- */}
          <div
            style={{
              display: 'flex',
              gap: 10,
              alignItems: 'flex-start',
              borderRadius: 14,
              padding: '12px 14px',
              marginBottom: 12,
              background: p.greenDeep,
              border: `1px solid ${p.recBd}`,
              color: p.recTx,
              fontSize: 11.5,
              lineHeight: 1.5,
            }}
          >
            <Info size={16} style={{ flexShrink: 0, marginTop: 1, color: p.av2 }} />
            <p style={{ margin: 0 }}>
              <b style={{ color: p.av2, fontWeight: 700 }}>Note:</b> Your Role, Status, Join Date, and Member ID are managed by club administrators.
              If you need to change these, please contact an admin.
            </p>
          </div>

          {/* ---------------- main grid ---------------- */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: 12 }} className="!grid-cols-1 lg:!grid-cols-[1fr_2fr]">
            {/* ---- left column: photo + club stats ---- */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
              <div style={{ borderRadius: 20, padding: 16, background: p.dark, color: p.tl, border: `1px solid ${p.border}` }}>
                <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 12 }}>Profile Photo</div>
                <div
                  style={{
                    aspectRatio: '1',
                    borderRadius: 16,
                    background: displayPhoto ? undefined : `linear-gradient(135deg, ${p.av2}, ${p.green})`,
                    backgroundImage: displayPhoto ? `url(${displayPhoto})` : undefined,
                    backgroundSize: 'cover',
                    backgroundPosition: 'center',
                    border: `1px solid ${p.border}`,
                    marginBottom: 12,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontSize: 48,
                    fontWeight: 700,
                    color: '#1b0c12',
                  }}
                >
                  {!displayPhoto && displayName.charAt(0).toUpperCase()}
                </div>
                <CloudinaryUpload
                  onUpload={(url: string) => setFormData((prev: any) => ({ ...prev, photo: url }))}
                  buttonText="Upload New Photo"
                />

                <div style={{ marginTop: 16, paddingTop: 16, borderTop: `1px solid ${p.border}`, display: 'flex', flexDirection: 'column', gap: 12 }}>
                  <div>
                    <span style={{ display: 'block', fontSize: 9.5, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '.06em', color: p.tsub, marginBottom: 6 }}>
                      Club Status
                    </span>
                    <div
                      style={{
                        display: 'inline-flex',
                        padding: '4px 11px',
                        borderRadius: 20,
                        fontSize: 10,
                        fontWeight: 700,
                        textTransform: 'uppercase',
                        letterSpacing: '.04em',
                        background: formData.status === 'active' ? p.greenDeep : 'rgba(224,138,114,.15)',
                        color: formData.status === 'active' ? p.av2 : '#e08a72',
                      }}
                    >
                      {formData.status || 'Pending'}
                    </div>
                  </div>
                  <div>
                    <span style={{ display: 'block', fontSize: 9.5, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '.06em', color: p.tsub, marginBottom: 4 }}>
                      Club Role
                    </span>
                    {/* Same label+color chip AdminMembers.tsx renders for
                        this same role_id — this is the fix: previously
                        this was plain text ("Member") decoupled from the
                        roles table, so it could silently disagree with
                        what the admin panel shows for this person. */}
                    <span
                      style={{
                        display: 'inline-flex',
                        fontSize: 10,
                        fontWeight: 700,
                        textTransform: 'uppercase',
                        letterSpacing: '.03em',
                        color: '#fff',
                        borderRadius: 8,
                        padding: '3px 9px',
                        background: roleColor,
                      }}
                    >
                      {roleLabel}
                    </span>
                  </div>

                  <div style={{ paddingTop: 12, borderTop: `1px solid ${p.border}` }}>
                    <span style={{ display: 'block', fontSize: 9.5, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '.06em', color: p.tsub, marginBottom: 6 }}>
                      Assigned Member ID
                    </span>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                      <BadgeCheck size={13} style={{ color: p.av2, flexShrink: 0 }} />
                      <span style={{ fontWeight: 700, fontSize: 13, letterSpacing: '.02em' }}>{formData.memberId || 'Not yet assigned'}</span>
                    </div>
                    <p style={{ fontSize: 9.5, color: p.tsub, marginTop: 4, lineHeight: 1.4 }}>Generated by the club admin panel. Separate from your Rotary Member ID.</p>
                  </div>

                  <div style={{ paddingTop: 12, borderTop: `1px solid ${p.border}` }}>
                    <span style={{ display: 'block', fontSize: 9.5, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '.06em', color: p.tsub, marginBottom: 10 }}>
                      Points
                    </span>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                        <span style={{ fontSize: 10.5, fontWeight: 700, display: 'flex', alignItems: 'center', gap: 4, color: '#e0b872' }}>
                          <Zap size={11} /> XP
                        </span>
                        <span style={{ fontWeight: 700, fontSize: 13 }}>{(formData.xp || 0).toLocaleString()}</span>
                      </div>
                      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                        <span style={{ fontSize: 10.5, fontWeight: 700, display: 'flex', alignItems: 'center', gap: 4, color: '#b494e0' }}>
                          <Star size={11} /> FP
                        </span>
                        <span style={{ fontWeight: 700, fontSize: 13 }}>{(formData.fp || 0).toLocaleString()}</span>
                      </div>
                      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                        <span style={{ fontSize: 10.5, fontWeight: 700, display: 'flex', alignItems: 'center', gap: 4, color: p.av2 }}>
                          <Trophy size={11} /> Level
                        </span>
                        <span style={{ fontWeight: 700, fontSize: 13 }}>{formData.level || 0}</span>
                      </div>
                    </div>
                    <Link
                      to="/dashboard/points"
                      style={{ display: 'block', textAlign: 'center', fontSize: 10.5, fontWeight: 700, color: p.green, marginTop: 12, textDecoration: 'none' }}
                    >
                      View Point History →
                    </Link>
                  </div>
                </div>
              </div>
            </div>

            {/* ---- right column: editable info + password ---- */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
              <ProfileSection title="Personal Information" p={p}>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }} className="!grid-cols-1 sm:!grid-cols-2">
                  <div className="rac-field" style={{ color: p.td }}>
                    <label style={{ color: p.mut }}>Full Name</label>
                    <input
                      type="text"
                      name="name"
                      value={formData.name || ''}
                      onChange={handleChange}
                      style={{ background: p.bg, border: `1px solid ${p.border}`, color: p.td }}
                    />
                  </div>
                  <div className="rac-field" style={{ color: p.td }}>
                    <label style={{ color: p.mut }}>Email Address</label>
                    <input type="email" value={formData.email || ''} disabled style={{ background: p.bg, border: `1px solid ${p.border}`, color: p.mut }} />
                    <p style={{ fontSize: 10, color: p.mut, marginTop: 5 }}>Email cannot be changed.</p>
                  </div>
                  <div className="rac-field" style={{ color: p.td }}>
                    <label style={{ color: p.mut }}>Phone Number</label>
                    <input
                      type="text"
                      name="phone"
                      value={formData.phone || ''}
                      onChange={handleChange}
                      placeholder="+880 1..."
                      style={{ background: p.bg, border: `1px solid ${p.border}`, color: p.td }}
                    />
                  </div>
                  <div className="rac-field" style={{ color: p.td }}>
                    <label style={{ color: p.mut }}>Date of Birth</label>
                    <input
                      type="date"
                      name="dob"
                      value={formData.dob || ''}
                      onChange={handleChange}
                      style={{ background: p.bg, border: `1px solid ${p.border}`, color: p.td }}
                    />
                  </div>
                  <div className="rac-field" style={{ color: p.td, gridColumn: '1 / -1' }}>
                    <label style={{ color: p.mut }}>Rotary Member ID</label>
                    <input
                      type="text"
                      name="rotaryMemberId"
                      value={formData.rotaryMemberId || ''}
                      onChange={handleChange}
                      placeholder="Official Rotary International member ID"
                      style={{ background: p.bg, border: `1px solid ${p.border}`, color: p.td }}
                    />
                    <p style={{ fontSize: 10, color: p.mut, marginTop: 5 }}>
                      Your official Rotary/Interact International ID — different from your Assigned Member ID shown on the left.
                    </p>
                  </div>
                </div>
                <div className="rac-field" style={{ color: p.td, marginTop: 14 }}>
                  <label style={{ color: p.mut }}>Address</label>
                  <textarea
                    name="address"
                    rows={3}
                    value={formData.address || ''}
                    onChange={handleChange}
                    style={{ background: p.bg, border: `1px solid ${p.border}`, color: p.td, resize: 'none' }}
                  />
                </div>
              </ProfileSection>

              <ProfileSection title="Academic & Emergency Info" p={p}>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }} className="!grid-cols-1 sm:!grid-cols-2">
                  <div className="rac-field" style={{ color: p.td }}>
                    <label style={{ color: p.mut }}>School / Institution</label>
                    <input
                      type="text"
                      name="school"
                      value={formData.school || ''}
                      onChange={handleChange}
                      style={{ background: p.bg, border: `1px solid ${p.border}`, color: p.td }}
                    />
                  </div>
                  <div className="rac-field" style={{ color: p.td }}>
                    <label style={{ color: p.mut }}>Grade / Class</label>
                    <input
                      type="text"
                      name="grade"
                      value={formData.grade || ''}
                      onChange={handleChange}
                      style={{ background: p.bg, border: `1px solid ${p.border}`, color: p.td }}
                    />
                  </div>
                  <div className="rac-field" style={{ color: p.td }}>
                    <label style={{ color: p.mut }}>Blood Group</label>
                    <select
                      name="bloodGroup"
                      value={formData.bloodGroup || ''}
                      onChange={handleChange}
                      style={{ background: p.bg, border: `1px solid ${p.border}`, color: p.td }}
                    >
                      <option value="">Select...</option>
                      {BLOOD_GROUPS.map((bg) => (
                        <option key={bg} value={bg}>
                          {bg}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div className="rac-field" style={{ color: p.td }}>
                    <label style={{ color: p.mut }}>Emergency Contact Phone</label>
                    <input
                      type="text"
                      name="emergencyPhone"
                      value={formData.emergencyPhone || ''}
                      onChange={handleChange}
                      style={{ background: p.bg, border: `1px solid ${p.border}`, color: p.td }}
                    />
                  </div>
                </div>
                <div className="rac-field" style={{ color: p.td, marginTop: 14 }}>
                  <label style={{ color: p.mut }}>Emergency Contact Details</label>
                  <textarea
                    name="emergencyDetails"
                    rows={2}
                    value={formData.emergencyDetails || ''}
                    onChange={handleChange}
                    placeholder="Name and relationship..."
                    style={{ background: p.bg, border: `1px solid ${p.border}`, color: p.td, resize: 'none' }}
                  />
                </div>
              </ProfileSection>

              {/* ---- password card: kept dark, like "Needs attention" ---- */}
              <div style={{ borderRadius: 20, padding: 16, background: p.dark, color: p.tl, border: `1px solid ${p.border}` }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
                  <span style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 13, fontWeight: 600 }}>
                    <Lock size={15} style={{ color: p.tsub }} /> Change Password
                  </span>
                  <span style={{ color: p.dots, fontSize: 15, letterSpacing: 1 }}>···</span>
                </div>

                <div style={{ display: 'flex', flexDirection: 'column', gap: 14, maxWidth: 380 }}>
                  <div className="rac-field">
                    <label style={{ color: p.tsub }}>Current Password</label>
                    <div style={{ position: 'relative' }}>
                      <input
                        type={showCurrentPw ? 'text' : 'password'}
                        value={currentPassword}
                        onChange={(e) => setCurrentPassword(e.target.value)}
                        autoComplete="current-password"
                        style={{ background: p.bg, border: `1px solid ${p.border}`, color: p.tl, paddingRight: 36, width: '100%' }}
                      />
                      <button
                        type="button"
                        onClick={() => setShowCurrentPw(!showCurrentPw)}
                        tabIndex={-1}
                        style={{ position: 'absolute', right: 10, top: '50%', transform: 'translateY(-50%)', background: 'none', border: 'none', color: p.tmid, cursor: 'pointer', padding: 0, display: 'flex' }}
                      >
                        {showCurrentPw ? <EyeOff size={15} /> : <Eye size={15} />}
                      </button>
                    </div>
                  </div>

                  <div className="rac-field">
                    <label style={{ color: p.tsub }}>New Password</label>
                    <div style={{ position: 'relative' }}>
                      <input
                        type={showNewPw ? 'text' : 'password'}
                        value={newPassword}
                        onChange={(e) => setNewPassword(e.target.value)}
                        autoComplete="new-password"
                        placeholder="Minimum 8 characters"
                        style={{ background: p.bg, border: `1px solid ${p.border}`, color: p.tl, paddingRight: 36, width: '100%' }}
                      />
                      <button
                        type="button"
                        onClick={() => setShowNewPw(!showNewPw)}
                        tabIndex={-1}
                        style={{ position: 'absolute', right: 10, top: '50%', transform: 'translateY(-50%)', background: 'none', border: 'none', color: p.tmid, cursor: 'pointer', padding: 0, display: 'flex' }}
                      >
                        {showNewPw ? <EyeOff size={15} /> : <Eye size={15} />}
                      </button>
                    </div>
                  </div>

                  <div className="rac-field">
                    <label style={{ color: p.tsub }}>Confirm New Password</label>
                    <input
                      type={showNewPw ? 'text' : 'password'}
                      value={confirmPassword}
                      onChange={(e) => setConfirmPassword(e.target.value)}
                      autoComplete="new-password"
                      style={{ background: p.bg, border: `1px solid ${p.border}`, color: p.tl, width: '100%' }}
                    />
                  </div>

                  <button
                    onClick={handlePasswordChange}
                    disabled={changingPassword}
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: 8,
                      background: p.green,
                      color: '#1b0c12',
                      border: 'none',
                      borderRadius: 12,
                      padding: '10px 18px',
                      fontSize: 13,
                      fontWeight: 700,
                      cursor: changingPassword ? 'default' : 'pointer',
                      opacity: changingPassword ? 0.7 : 1,
                      alignSelf: 'flex-start',
                    }}
                  >
                    {changingPassword ? <Loader2 size={16} className="animate-spin" /> : <Lock size={16} />}
                    Update Password
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

/** Reused "light card, section header + border-bottom rule" wrapper —
 * same visual weight as DashboardHome's p.lightCard cards (Tracking /
 * Attendance rate), just tall enough to hold a form grid. Kept local
 * to this file since nothing else needs it yet; promote to a shared
 * component if a third page ends up wanting the same shape. */
function ProfileSection({ title, p, children }: { title: string; p: any; children: React.ReactNode }) {
  return (
    <div style={{ borderRadius: 20, padding: 16, background: p.lightCard, color: p.td }}>
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          marginBottom: 14,
          paddingBottom: 12,
          borderBottom: `1px solid ${p.border}`,
        }}
      >
        <span style={{ fontSize: 13, fontWeight: 600 }}>{title}</span>
        <span style={{ color: '#b0a7aa', fontSize: 15, letterSpacing: 1 }}>···</span>
      </div>
      {children}
    </div>
  );
}
